/// Flutter icons PrivPay
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PrivPay
///      fonts:
///       - asset: fonts/PrivPay.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PrivPay {
  PrivPay._();

  static const _kFontFam = 'PrivPay';
  static const String? _kFontPkg = null;

  static const IconData account = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_1 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faqs = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_97 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_127 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_1 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layer_2 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_icon = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacy_policy_1 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rate_1 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData splash_vector = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData start_screen_vector = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData suport_icon = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terms_and_conditions = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData e_wallet_pana_1 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privpay_logo_01_1 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
